
const fs = require('fs');
const fsp = require('fs/promises');
const path = require('path');
const crypto = require('crypto');

// ============ CONFIG ============
const CONFIG = {
  defaultSkillsDir: path.join(process.cwd(), 'skills'),
  defaultVersion: '1.0.0',
  schemaVersion: 1,
  overwritePolicy: 'reject',        // reject | backup | force
  backupDir: path.join(process.cwd(), '.skill-backups'),
  maxBackups: 20,
  generateTests: true,
  generateDocs: true,
  generateManifest: true,
  validateSyntax: true,
  registryFile: path.join(process.cwd(), '.skills-registry.json'),
  logLevel: process.env.LOG_LEVEL || 'info',
};

// ============ LOGGER ============
const LEVELS = { error: 0, warn: 1, info: 2, debug: 3 };
const CL = LEVELS[CONFIG.logLevel] || 2;
function log(level, msg, meta) {
  if (LEVELS[level] > CL) return;
  const line = meta
    ? `[SkillBuilder] ${level.toUpperCase()} ${msg} ${JSON.stringify(meta)}`
    : `[SkillBuilder] ${level.toUpperCase()} ${msg}`;
  (level === 'error' ? process.stderr : process.stdout).write(line + '\n');
}

// ============ TEMPLATES ============
// Each template returns the code for a skill module
const TEMPLATES = {
  basic: ({ name, description, category, version }) => `
/**
 * ${name}
 * ${description}
 * @generated by SkillBuilderAgent
 * @version ${version}
 * @category ${category}
 */

module.exports = {
  name: '${name}',
  version: '${version}',
  category: '${category}',
  description: '${description}',

  schema: {
    type: 'object',
    properties: {},
    required: [],
  },

  async run(args = {}) {
    return {
      success: true,
      skill: '${name}',
      args,
      timestamp: new Date().toISOString(),
    };
  },

  async health() {
    return { ok: true, skill: '${name}' };
  },
};
`.trim(),

  analyzer: ({ name, description, category, version }) => `
/**
 * ${name} (Analyzer)
 * ${description}
 * @version ${version}
 */

module.exports = {
  name: '${name}',
  version: '${version}',
  category: '${category}',
  description: '${description}',
  type: 'analyzer',

  schema: {
    type: 'object',
    properties: {
      target: { type: 'string' },
      deep: { type: 'boolean', default: false },
    },
    required: ['target'],
  },

  async run({ target, deep = false } = {}) {
    if (!target) {
      return { success: false, error: 'target required' };
    }

    const findings = [];
    const startedAt = Date.now();

    // TODO: implement analysis logic
    // Example:
    // findings.push({ id: 'x', severity: 'info', message: '...' });

    return {
      success: true,
      skill: '${name}',
      target,
      deep,
      findings,
      count: findings.length,
      durationMs: Date.now() - startedAt,
      timestamp: new Date().toISOString(),
    };
  },

  async health() {
    return { ok: true, skill: '${name}', type: 'analyzer' };
  },
};
`.trim(),

  tool: ({ name, description, category, version }) => `
/**
 * ${name} (Tool)
 * ${description}
 * @version ${version}
 */

module.exports = {
  name: '${name}',
  version: '${version}',
  category: '${category}',
  description: '${description}',
  type: 'tool',

  schema: {
    type: 'object',
    properties: {
      input: { type: 'string' },
      options: { type: 'object' },
    },
    required: ['input'],
  },

  async run({ input, options = {} } = {}) {
    if (input == null) {
      return { success: false, error: 'input required' };
    }

    const startedAt = Date.now();

    // TODO: implement tool logic
    const output = input;

    return {
      success: true,
      skill: '${name}',
      input,
      output,
      options,
      durationMs: Date.now() - startedAt,
    };
  },

  async health() {
    return { ok: true, skill: '${name}', type: 'tool' };
  },
};
`.trim(),

  'api-client': ({ name, description, category, version }) => `
/**
 * ${name} (API Client)
 * ${description}
 * @version ${version}
 */

const https = require('https');

module.exports = {
  name: '${name}',
  version: '${version}',
  category: '${category}',
  description: '${description}',
  type: 'api-client',

  config: {
    baseUrl: process.env.${name.toUpperCase()}_BASE_URL || '',
    timeoutMs: 15000,
    headers: {},
  },

  schema: {
    type: 'object',
    properties: {
      path: { type: 'string' },
      method: { type: 'string', default: 'GET' },
      body: { type: 'object' },
    },
    required: ['path'],
  },

  async request({ path, method = 'GET', body } = {}) {
    const url = new URL(path, this.config.baseUrl);

    return new Promise((resolve) => {
      const req = https.request(
        {
          method,
          hostname: url.hostname,
          path: url.pathname + url.search,
          headers: { 'Content-Type': 'application/json', ...this.config.headers },
          timeout: this.config.timeoutMs,
        },
        (res) => {
          let data = '';
          res.on('data', (c) => (data += c));
          res.on('end', () => {
            try {
              resolve({ status: res.statusCode, body: JSON.parse(data) });
            } catch {
              resolve({ status: res.statusCode, body: data });
            }
          });
        }
      );

      req.on('error', (err) => resolve({ error: err.message }));
      req.on('timeout', () => { req.destroy(); resolve({ error: 'timeout' }); });

      if (body) req.write(JSON.stringify(body));
      req.end();
    });
  },

  async run(args) {
    const res = await this.request(args);
    return { success: !res.error, skill: '${name}', ...res };
  },

  async health() {
    if (!this.config.baseUrl) return { ok: false, reason: 'baseUrl not set' };
    return { ok: true, skill: '${name}', baseUrl: this.config.baseUrl };
  },
};
`.trim(),

  transformer: ({ name, description, category, version }) => `
/**
 * ${name} (Transformer)
 * ${description}
 * @version ${version}
 */

module.exports = {
  name: '${name}',
  version: '${version}',
  category: '${category}',
  description: '${description}',
  type: 'transformer',

  schema: {
    type: 'object',
    properties: {
      input: {},
      options: { type: 'object' },
    },
    required: ['input'],
  },

  async transform(input, options = {}) {
    // TODO: implement transform logic
    return input;
  },

  async run({ input, options = {} } = {}) {
    if (input == null) return { success: false, error: 'input required' };

    const startedAt = Date.now();
    const output = await this.transform(input, options);

    return {
      success: true,
      skill: '${name}',
      output,
      durationMs: Date.now() - startedAt,
    };
  },

  async health() {
    return { ok: true, skill: '${name}', type: 'transformer' };
  },
};
`.trim(),

  'multi-step': ({ name, description, category, version }) => `
/**
 * ${name} (Multi-step pipeline)
 * ${description}
 * @version ${version}
 */

module.exports = {
  name: '${name}',
  version: '${version}',
  category: '${category}',
  description: '${description}',
  type: 'pipeline',

  steps: [],

  schema: {
    type: 'object',
    properties: {
      input: {},
      steps: { type: 'array' },
    },
    required: ['input'],
  },

  register(stepName, fn) {
    this.steps.push({ name: stepName, fn });
    return this;
  },

  async run({ input, steps = null } = {}) {
    const startedAt = Date.now();
    const selected = steps
      ? this.steps.filter((s) => steps.includes(s.name))
      : this.steps;

    let current = input;
    const trace = [];

    for (const step of selected) {
      try {
        const stepStart = Date.now();
        current = await step.fn(current);
        trace.push({ step: step.name, ok: true, ms: Date.now() - stepStart });
      } catch (err) {
        trace.push({ step: step.name, ok: false, error: err.message });
        return { success: false, skill: '${name}', error: err.message, trace };
      }
    }

    return {
      success: true,
      skill: '${name}',
      output: current,
      trace,
      durationMs: Date.now() - startedAt,
    };
  },

  async health() {
    return { ok: true, skill: '${name}', steps: this.steps.length };
  },
};
`.trim(),
};

// ============ HELPERS ============
function uid(p = 's') {
  return `${p}_${crypto.randomBytes(4).toString('hex')}`;
}

function nowIso() {
  return new Date().toISOString();
}

function sanitize(name) {
  return String(name || '')
    .replace(/[^a-z0-9_-]/gi, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase();
}

function toClassName(name) {
  return sanitize(name)
    .split(/[_-]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

function toPascalCase(name) {
  return toClassName(name);
}

async function ensureDir(dir) {
  await fsp.mkdir(dir, { recursive: true });
}

async function atomicWrite(file, data) {
  await ensureDir(path.dirname(file));
  const tmp = `${file}.tmp-${process.pid}-${Date.now()}`;
  await fsp.writeFile(tmp, data, 'utf8');
  await fsp.rename(tmp, file);
}

function validateJsSyntax(code, filename = 'skill.js') {
  try {
    // Use new Function to compile-check (avoid running)
    // eslint-disable-next-line no-new-func
    new Function('module', 'exports', 'require', code);
    return { ok: true };
  } catch (err) {
    return { ok: false, error: err.message, filename };
  }
}

// ============ TEST GENERATOR ============
function buildTestCode(skillName, template, version) {
  return `
const test = require('node:test');
const assert = require('node:assert');
const skill = require('../skills/${skillName}.js');

test('${skillName} — metadata', () => {
  assert.strictEqual(skill.name, '${skillName}');
  assert.strictEqual(skill.version, '${version}');
  assert.ok(skill.description);
  assert.strictEqual(typeof skill.run, 'function');
});

test('${skillName} — health()', async () => {
  if (typeof skill.health !== 'function') return;
  const h = await skill.health();
  assert.ok(h);
  assert.strictEqual(typeof h.ok, 'boolean');
});

test('${skillName} — run() basic', async () => {
  try {
    const res = await skill.run({});
    assert.ok(res);
    assert.strictEqual(typeof res.success, 'boolean');
  } catch (err) {
    // Template may require args — acceptable
    assert.ok(err);
  }
});
`.trim();
}

// ============ DOC GENERATOR ============
function buildReadme(skill, meta) {
  const lines = [];
  lines.push(`# 🧩 ${meta.name}`);
  lines.push('');
  lines.push(`> ${meta.description}`);
  lines.push('');
  lines.push(`**Version:** \`${meta.version}\`  `);
  lines.push(`**Category:** \`${meta.category}\`  `);
  lines.push(`**Template:** \`${meta.template}\`  `);
  lines.push(`**Generated:** ${meta.generatedAt}  `);
  lines.push('');
  lines.push('## 📦 Usage');
  lines.push('');
  lines.push('```js');
  lines.push(`const skill = require('./skills/${meta.name}.js');`);
  lines.push('');
  lines.push(`const result = await skill.run({ /* args */ });`);
  lines.push('console.log(result);');
  lines.push('```');
  lines.push('');

  if (meta.schema?.properties) {
    lines.push('## 🔤 Input Schema');
    lines.push('');
    lines.push('| Field | Type | Required |');
    lines.push('|---|---|---|');
    const required = new Set(meta.schema.required || []);
    for (const [k, v] of Object.entries(meta.schema.properties)) {
      lines.push(`| \`${k}\` | ${v.type || 'any'} | ${required.has(k) ? '✅' : '❌'} |`);
    }
    lines.push('');
  }

  lines.push('## 🧪 Testing');
  lines.push('');
  lines.push('```bash');
  lines.push(`node --test tests/${meta.name}.test.js`);
  lines.push('```');
  lines.push('');
  lines.push('---');
  lines.push(`_Generated by SkillBuilderAgent on ${meta.generatedAt}_`);
  return lines.join('\n');
}

// ============ MANIFEST ============
function buildManifest(meta) {
  return {
    schemaVersion: CONFIG.schemaVersion,
    name: meta.name,
    version: meta.version,
    category: meta.category,
    description: meta.description,
    template: meta.template,
    tags: meta.tags || [],
    author: meta.author || 'SkillBuilderAgent',
    generatedAt: meta.generatedAt,
    files: meta.files,
    dependencies: meta.dependencies || [],
    schema: meta.schema || null,
  };
}

// ============ REGISTRY ============
async function loadRegistry() {
  try {
    const raw = await fsp.readFile(CONFIG.registryFile, 'utf8');
    return JSON.parse(raw);
  } catch {
    return { version: CONFIG.schemaVersion, skills: {}, updatedAt: nowIso() };
  }
}

async function saveRegistry(reg) {
  reg.updatedAt = nowIso();
  await atomicWrite(CONFIG.registryFile, JSON.stringify(reg, null, 2));
}

// ============ BACKUP ============
async function backupFile(file) {
  try {
    if (!fs.existsSync(file)) return null;
    await ensureDir(CONFIG.backupDir);
    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    const dest = path.join(
      CONFIG.backupDir,
      `${path.basename(file)}.${stamp}.bak`
    );
    await fsp.copyFile(file, dest);

    // Rotate
    const all = (await fsp.readdir(CONFIG.backupDir))
      .filter((f) => f.endsWith('.bak'))
      .sort();
    if (all.length > CONFIG.maxBackups) {
      for (const f of all.slice(0, all.length - CONFIG.maxBackups)) {
        await fsp.unlink(path.join(CONFIG.backupDir, f)).catch(() => {});
      }
    }
    return dest;
  } catch (err) {
    log('warn', 'backup failed', { err: err.message });
    return null;
  }
}

// ============ MAIN CLASS ============
class SkillBuilderAgent {
  constructor() {
    this.stats = {
      built: 0,
      saved: 0,
      updated: 0,
      deleted: 0,
      failed: 0,
      byTemplate: {},
      byCategory: {},
    };
  }

  /**
   * Build skill code (in-memory, no disk write).
   */
  buildSkill(skillName, options = {}) {
    const name = sanitize(skillName);
    if (!name) throw new Error('Invalid skill name');

    const templateKey = options.template || 'basic';
    const template = TEMPLATES[templateKey];
    if (!template) throw new Error(`Unknown template: ${templateKey}`);

    const description = options.description ||
      `${name} generated by SkillBuilderAgent`;
    const category = options.category || 'general';
    const version = options.version || CONFIG.defaultVersion;

    const code = template({
      name,
      description,
      category,
      version,
      options,
    });

    // Validate syntax
    if (CONFIG.validateSyntax) {
      const v = validateJsSyntax(code, `${name}.js`);
      if (!v.ok) {
        throw Object.assign(
          new Error(`Generated code has syntax error: ${v.error}`),
          { code: 'SYNTAX_ERROR' }
        );
      }
    }

    const result = {
      name,
      fileName: `${name}.js`,
      code,
      template: templateKey,
      category,
      description,
      version,
      generatedAt: nowIso(),
    };

    this.stats.built++;
    this.stats.byTemplate[templateKey] = (this.stats.byTemplate[templateKey] || 0) + 1;
    this.stats.byCategory[category] = (this.stats.byCategory[category] || 0) + 1;

    return result;
  }

  /**
   * Preview without writing.
   */
  preview(skillName, options = {}) {
    const built = this.buildSkill(skillName, options);
    return {
      ...built,
      preview: true,
      lines: built.code.split('\n').length,
    };
  }

  /**
   * Save skill to disk (with tests, docs, manifest).
   */
  async saveSkill(skillName, skillsDir, options = {}) {
    const dir = skillsDir || CONFIG.defaultSkillsDir;
    const built = this.buildSkill(skillName, options);

    const skillFile = path.join(dir, built.fileName);
    const manifestFile = path.join(dir, `${built.name}.manifest.json`);
    const testFile = path.join(
      options.testsDir || path.join(process.cwd(), 'tests'),
      `${built.name}.test.js`
    );
    const docFile = path.join(
      options.docsDir || path.join(dir, 'docs'),
      `${built.name}.md`
    );

    // Overwrite check
    if (fs.existsSync(skillFile) && CONFIG.overwritePolicy === 'reject' && !options.force) {
      return {
        success: false,
        error: `Skill already exists: ${skillFile}`,
        hint: 'Pass { force: true } or { overwrite: "backup" }',
      };
    }

    // Backup existing files
    const backups = [];
    if (fs.existsSync(skillFile)) {
      const b = await backupFile(skillFile);
      if (b) backups.push(b);
    }

    await ensureDir(dir);

    // Write skill file
    await atomicWrite(skillFile, built.code);

    const written = { skill: skillFile, extras: [] };

    // Tests
    if (options.tests !== false && CONFIG.generateTests) {
      const testCode = buildTestCode(built.name, built.template, built.version);
      await atomicWrite(testFile, testCode);
      written.extras.push({ type: 'test', file: testFile });
    }

    // Docs
    if (options.docs !== false && CONFIG.generateDocs) {
      const readme = buildReadme(built, {
        name: built.name,
        description: built.description,
        version: built.version,
        category: built.category,
        template: built.template,
        generatedAt: built.generatedAt,
        schema: options.schema || null,
      });
      await atomicWrite(docFile, readme);
      written.extras.push({ type: 'doc', file: docFile });
    }

    // Manifest
    if (options.manifest !== false && CONFIG.generateManifest) {
      const manifest = buildManifest({
        ...built,
        files: [skillFile, testFile, docFile].filter((f) => fs.existsSync(f)),
        dependencies: options.dependencies || [],
        tags: options.tags || [],
        author: options.author,
        schema: options.schema || null,
      });
      await atomicWrite(manifestFile, JSON.stringify(manifest, null, 2));
      written.extras.push({ type: 'manifest', file: manifestFile });
    }

    // Update registry
    const reg = await loadRegistry();
    const existing = reg.skills[built.name];
    reg.skills[built.name] = {
      name: built.name,
      version: built.version,
      category: built.category,
      template: built.template,
      description: built.description,
      file: skillFile,
      addedAt: existing?.addedAt || nowIso(),
      updatedAt: nowIso(),
    };
    await saveRegistry(reg);

    this.stats.saved++;
    if (existing) this.stats.updated++;

    log('info', 'skill saved', { name: built.name, file: skillFile });

    return {
      success: true,
      file: skillFile,
      name: built.name,
      version: built.version,
      backups,
      files: written,
      manifest: path.join(dir, `${built.name}.manifest.json`),
    };
  }

  /**
   * Bulk save multiple skills.
   */
  async saveMany(skillNames, skillsDir, options = {}) {
    const results = [];
    for (const name of skillNames) {
      try {
        results.push(await this.saveSkill(name, skillsDir, options));
      } catch (err) {
        this.stats.failed++;
        results.push({ success: false, name, error: err.message });
      }
    }
    return results;
  }

  /**
   * Update existing skill (keeps version bump).
   */
  async updateSkill(skillName, options = {}) {
    const dir = options.skillsDir || CONFIG.defaultSkillsDir;
    const existing = await this.getSkill(skillName);
    if (!existing) {
      return { success: false, error: 'Skill not found' };
    }

    const currentVersion = existing.version || '1.0.0';
    const nextVersion = bumpVersion(currentVersion, options.bump || 'patch');

    return this.saveSkill(skillName, dir, {
      ...options,
      version: nextVersion,
      force: true,
      overwrite: 'backup',
    });
  }

  /**
   * Delete a skill + its extras.
   */
  async deleteSkill(skillName, options = {}) {
    const name = sanitize(skillName);
    const dir = options.skillsDir || CONFIG.defaultSkillsDir;
    const files = [
      path.join(dir, `${name}.js`),
      path.join(dir, `${name}.manifest.json`),
      path.join(options.testsDir || path.join(process.cwd(), 'tests'), `${name}.test.js`),
      path.join(options.docsDir || path.join(dir, 'docs'), `${name}.md`),
    ];

    const deleted = [];
    const backups = [];

    for (const f of files) {
      if (!fs.existsSync(f)) continue;
      const b = await backupFile(f);
      if (b) backups.push(b);
      await fsp.unlink(f);
      deleted.push(f);
    }

    const reg = await loadRegistry();
    delete reg.skills[name];
    await saveRegistry(reg);

    this.stats.deleted++;
    log('info', 'skill deleted', { name, count: deleted.length });

    return { success: true, name, deleted, backups };
  }

  /**
   * List skills (from registry).
   */
  async listSkills(filter = {}) {
    const reg = await loadRegistry();
    let list = Object.values(reg.skills);

    if (filter.category) list = list.filter((s) => s.category === filter.category);
    if (filter.template) list = list.filter((s) => s.template === filter.template);
    if (filter.name) {
      const re = new RegExp(filter.name, 'i');
      list = list.filter((s) => re.test(s.name));
    }

    return list.sort((a, b) => a.name.localeCompare(b.name));
  }

  /**
   * Get one skill (from registry + filesystem).
   */
  async getSkill(skillName) {
    const reg = await loadRegistry();
    const meta = reg.skills[sanitize(skillName)];
    if (!meta) return null;

    try {
      const code = await fsp.readFile(meta.file, 'utf8');
      return { ...meta, code };
    } catch {
      return meta;
    }
  }

  /**
   * Verify skill loads & has expected shape.
   */
  async verifySkill(skillName, options = {}) {
    const path = options.file ||
      path.join(options.skillsDir || CONFIG.defaultSkillsDir, `${sanitize(skillName)}.js`);

    if (!fs.existsSync(path)) {
      return { ok: false, error: 'file not found', path };
    }

    // Syntax check
    const code = await fsp.readFile(path, 'utf8');
    const syn = validateJsSyntax(code, path);
    if (!syn.ok) return { ok: false, error: syn.error };

    // Load & shape check
    try {
      delete require.cache[require.resolve(path)];
      const mod = require(path);

      const issues = [];
      if (!mod.name) issues.push('missing name');
      if (!mod.description) issues.push('missing description');
      if (typeof mod.run !== 'function') issues.push('missing run()');
      if (typeof mod.health !== 'function') issues.push('(optional) missing health()');

      return {
        ok: issues.length === 0,
        name: mod.name,
        version: mod.version,
        issues,
        path,
      };
    } catch (err) {
      return { ok: false, error: err.message, path };
    }
  }

  /**
   * Verify all skills in registry.
   */
  async verifyAll(options = {}) {
    const list = await this.listSkills(options.filter || {});
    const results = [];
    for (const s of list) {
      results.push(await this.verifySkill(s.name, options));
    }
    return {
      ok: results.every((r) => r.ok),
      total: results.length,
      passed: results.filter((r) => r.ok).length,
      failed: results.filter((r) => !r.ok),
      results,
    };
  }

  /**
   * Detect if skill has missing dependencies.
   */
  async checkDependencies(skillName, options = {}) {
    const skill = await this.getSkill(skillName);
    if (!skill || !skill.code) return { ok: true, missing: [] };

    const deps = [];
    const re = /require\s*\(\s*['"]([^'"]+)['"]\s*\)/g;
    let m;
    while ((m = re.exec(skill.code))) deps.push(m[1]);

    const missing = [];
    for (const dep of deps) {
      if (dep.startsWith('.')) continue;    // local imports — skip
      try {
        require.resolve(dep, { paths: [process.cwd()] });
      } catch {
        missing.push(dep);
      }
    }

    return { ok: missing.length === 0, dependencies: deps, missing };
  }

  /**
   * Available templates.
   */
  listTemplates() {
    return Object.keys(TEMPLATES).map((key) => ({
      key,
      description: TEMPLATE_DESCRIPTIONS[key] || '',
    }));
  }

  /**
   * Stats.
   */
  getStats() {
    return { ...this.stats };
  }
}

// ============ TEMPLATE DESCRIPTIONS ============
const TEMPLATE_DESCRIPTIONS = {
  basic: 'Minimal skill scaffold',
  analyzer: 'Analysis skill returning findings',
  tool: 'Input → output transformation tool',
  'api-client': 'HTTP client wrapper',
  transformer: 'Pure data transformer',
  'multi-step': 'Pipeline with step registration',
};

// ============ VERSION BUMP ============
function bumpVersion(v, type = 'patch') {
  const [major, minor, patch] = String(v || '1.0.0')
    .split('.')
    .map((n) => parseInt(n, 10) || 0);

  if (type === 'major') return `${major + 1}.0.0`;
  if (type === 'minor') return `${major}.${minor + 1}.0`;
  return `${major}.${minor}.${patch + 1}`;
}

// ============ EXPORT ============
const agent = new SkillBuilderAgent();
agent.TEMPLATES = TEMPLATES;
agent.CONFIG = CONFIG;
agent.bumpVersion = bumpVersion;
agent.sanitize = sanitize;

module.exports = agent;
